version: '3.8'
services:
  inference:
    build: ./api/inference
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  gateway:
    build: ./api/gateway
    ports:
      - "8080:8080"
    environment:
      - INFERENCE_URL=http://inference:8000
      - TZ=Asia/Seoul
    depends_on:
      inference:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  snapshot-worker:
    build: ./pipeline/snapshot
    environment:
      - OUTPUT_DIR=/srv/out
      - TZ=Asia/Seoul
    volumes:
      - ./data/snapshots:/srv/out

  feeders:
    build: ./pipeline/feeders
    environment:
      - OUT_DIR=/data
      - TZ=Asia/Seoul
    volumes:
      - ./data/feeds:/data

# Docker Compose automatically creates a bridge network for this stack.
# Services can refer to each other by their service name, e.g. "http://inference:8000".